version: '3.9'

services:

  mysql:
    image: mysql:8.4
    container_name: tms-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskManager
      MYSQL_USER: vaibhaovk
      MYSQL_PASSWORD: vaibhao

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - tms-network

  backend:
    build: .
    container_name: tms-backend

    restart: always

    depends_on:
      - mysql

    env_file:
      - .env

    ports:
      - "8080:8080"

    networks:
      - tms-network

volumes:
  mysql-data:

networks:
  tms-network: